version: 0.2

phases:
  install:
    commands:
    - echo "⚡ Installation des dépendances..."
    - npm install

  build:
    commands:
    - echo "⚙️ Build du projet Next.js..."
    - npm run build
    - npm run export

  post_build:
    commands:
    - echo "📤 Déploiement vers S3..."
    - aws s3 sync out/ s3://thegroomlab --delete
    - echo "♻️ Invalidation CloudFront..."
    - aws cloudfront create-invalidation --distribution-id E1WL1KCM9ECW9J --paths "/*"

artifacts:
  files:
  - '**/*'
  base-directory: out
